"""Added gender column to user table

Revision ID: fb97fb631646
Revises: 
Create Date: 2024-11-29 17:47:33.772689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb97fb631646'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=False))
        batch_op.add_column(sa.Column('activity_level', sa.Enum('sedentary', 'lightly_active', 'moderately_active', 'very_active', 'super_active', name='activitylevel'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('activity_level')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
